/**
 * This file is generated from global.css.
 * Do not edit manually.
 */

export const Colors = {
  light: {
    background: "#e7e5e4",
    foreground: "#1e293b",
    card: "#f5f5f4",
    cardForeground: "#1e293b",
    popover: "#f5f5f4",
    popoverForeground: "#1e293b",
    primary: "#bb4d00",
    primaryForeground: "#ffffff",
    secondary: "#d6d3d1",
    secondaryForeground: "#4b5563",
    muted: "#e7e5e4",
    mutedForeground: "#6b7280",
    accent: "#f3e5f5",
    accentForeground: "#374151",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#d6d3d1",
    input: "#d6d3d1",
    ring: "#6366f1",
    chart1: "#6366f1",
    chart2: "#4f46e5",
    chart3: "#4338ca",
    chart4: "#3730a3",
    chart5: "#312e81",
    sidebar: "#d6d3d1",
    sidebarForeground: "#1e293b",
    sidebarPrimary: "#6366f1",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#f3e5f5",
    sidebarAccentForeground: "#374151",
    sidebarBorder: "#d6d3d1",
    sidebarRing: "#6366f1",
    fontSans: "#NaNNaNNaN",
    fontSerif: "#NaNNaNNaN",
    fontMono: "#NaNNaNNaN",
    radius: "#NaNNaNNaN",
    shadowX: "#NaNNaNNaN",
    shadowY: "#NaNNaNNaN",
    shadowBlur: "#NaNNaNNaN",
    shadowSpread: "#NaNNaNNaN",
    shadowOpacity: "#NaNNaNNaN",
    shadowColor: "#NaNNaNNaN",
    shadow2xs: "#NaNNaNNaN",
    shadowXs: "#NaNNaNNaN",
    shadowSm: "#NaNNaNNaN",
    shadow: "#NaNNaNNaN",
    shadowMd: "#NaNNaNNaN",
    shadowLg: "#NaNNaNNaN",
    shadowXl: "#NaNNaNNaN",
    shadow2xl: "#NaNNaNNaN",
    trackingNormal: "#NaNNaNNaN",
    spacing: "#NaNNaNNaN",
  },
  dark: {
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#0a0a0a",
    cardForeground: "#fafafa",
    popover: "#0a0a0a",
    popoverForeground: "#fafafa",
    primary: "#fafafa",
    primaryForeground: "#171717",
    secondary: "#262626",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    accent: "#262626",
    accentForeground: "#fafafa",
    destructive: "#e14e4e",
    border: "#262626",
    input: "#262626",
    ring: "#737373",
    chart1: "#2662d9",
    chart2: "#2eb88a",
    chart3: "#e88c30",
    chart4: "#af57db",
    chart5: "#e23670",
  },
} as const;
